### ISSUE TITLE
2022-05-08 회의록

### ISSUE THREAD

**Issue by ParkSunJin** [dev-sian/meetings#1]
## 프젝

- 오늘 하나 간단한거 완성해버릴거야
- 5,6~7월에 하나씩 할거임

## 알고리즘

- 각자 1일1문제

## 개념공부

- 스프링 - 프젝 진행하면서 필요한거 정리하고 공유

## 면접준비(각자)

- http, 객체지향 개념
- 운영체제, 네트워크 ,데이터베이스

## TODO
- [x] 쿼리 매핑 및 **정리(meetings)** @ybkim-dev
    - [x] has one (association), has many (collection) - [참고](https://goodgid.github.io/Mybatis-Association-Collection-Part-1/) 
    - [x] 상속관계 매핑 (discriminator, case) - [참고](https://www.devkuma.com/docs/mybatis/%EC%A1%B0%EA%B1%B4%EC%97%90-%EB%94%B0%EB%9D%BC-%EB%8B%A4%EB%A5%B8-%ED%81%B4%EB%9E%98%EC%8A%A4%EC%97%90-%EB%A7%A4%ED%95%91/) 
- [x] 로깅(쿼리), slf4j ? logback VS. log4j VS. log4j2 **정리(meetings)** @ParkSunJin 
- [x] Comment CRUD @ybkim-dev 
- [ ] ~~GeneralPost, User CRUD @ParkSunJin~~
- [ ] ~~gradle 정리 @wallflower1331~~
