### ISSUE TITLE
2022-05-13 회의록

### ISSUE THREAD

**Issue by ParkSunJin** [dev-sian/meetings#14]
## 영반 리뷰
1. 응답 코드 (Http Method 맞춰서 사용)
   - ResponseEntity.created, nocontent .etc.
2. Model Mapping 방벙
   1. 생성자
   2. ModelMapper
   3. Util Class(Converter)
   4. Map Struct
3. CommentConverter

## 떤딘 리뷰
1. Post를 상속으로 ReviewPost, GeneralPost로 나눴는데, Post create, update, delete api 만들때 프론트에서 객체 넘기면 서버에 PostBO에서는 각 메소드안에서 또 PostType으로 switch문으로 분기해서 각각 처리하는 코드를 짜는게 맞는건지? 그럼 각 create, update, delete 메소드마다 반복되는 코드도 생기고 각 메소드가 너무 길어지는 것은 아닌지..

   - BO도 상속으로 나눠서 처리하기로 함. PostBO를 상속받는 ReviewPostBO, GeneralPostBO 등을 만들어서 각 상황에 적절한 BO를 선택해서 사용하도록 함.

2. Post와 Post dto 등에서 writer 필드가 있는데, 이때 User 타입 또는 UserReadDto 타입으로 가지고 있는게 나을지, 아니면 Integer 타입으로 writerId 만 가지고 있는게 나을지?

   1) User 또는 UserReadDto 타입으로 가지고 있으면 User 정보가 수정된 경우, User 를 가지고 있는 다른 객체들도 모두 수정을 해줘야 함

   2) writerId 만 가지고 있으면 해당 유저의 프로필 등의 정보를 바로 가져오지 못하고 필요한 경우 그때그때 또 디비를 조회해서 조인연산을 해줘야 될 수도 있음.

   - 회의 결과 writerId를 가지고 있기로 함..

3. postFacade에서 postbo로 넘길때, posts를 넘기는게 나은지, 아님 boardId를 넘기는게 나은지?

   - posts를 postFacade에서 받아와서 posts를 넘기기로 결정. 안그럼 각 postBO에 posts를 디비 조회해서 가져오는 코드가 반복됨 

4. postModelConverter 문제

   - postModelConverter를 하나 두고, PostReadDTO를 받아와서 reviewInfo는 new ReviewInfoReadDTO(파라미터에 와랄라 넣기) 
   - modelConverter를 게시판 종류마다 만들기

   -> 꼭 modelConverter를 사용해야한다고 생각했는데, 그냥 생성자를 사용하면 된다는 것을 깨달음..

5. No serializer found for class GeneralPostReadDTO and no properties discovered to create BeanSerializer
   이런 에러가 났는데
   https://ksl2950.tistory.com/55
   이거 보고 해결함..당최 뭔지 찾아보기..

6. reviewPost create 할때 reviewInfo insert 하기 위해서 postId 넣어야 되는데 이걸 어케 구하지???

   - insert/update 등을 실행하고서 결과를 확인하는 방법이 다 있었음!
     [[쿼리 실행 후 결과값 가져오기](https://moonsiri.tistory.com/18)](https://moonsiri.tistory.com/18)

7. review post create 할때 리퀘스트 바디에 createDTO 받는데 reviewInfo는 어케받지..?
    - https://kok202.tistory.com/228

## TODO
- [x]  postFacade에서 switch문에서 postBO들 빈으로 처리하기 @ParkSunJin 
- [x] PostBO Abstract 빼고 나머지에서 super.어쩌구 쓰기 @ParkSunJin 
- [x] #15
- [ ] 스프링 시큐리티 적용 차주 과제 @ybkim-dev 
    - [ ] 로그인
    - [ ] 회원가입
    - [ ] 세션관리? API 별로 권한체크  
- [ ] AOP @ParkSunJin 
    - [ ]  exception handler - 에러 로깅
    - [ ] 트랜잭션 처리
- [ ] 에러 처리 @ParkSunJin 
- [x]  Post API  @ParkSunJin
- [ ] User API @ybkim-dev 
- [ ] gradle 정리 @wallflower1331 @wallflower1331 @wallflower1331 @wallflower1331 @wallflower1331 @wallflower1331 @wallflower1331
